version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: hubeleza-api
    restart: unless-stopped
    ports:
      - '4000:4000'
    environment:
      - PORT=4000
    env_file:
      - .env
    networks:
      - hubeleza
      - evolution-net

networks:
  hubeleza:
    external: true
  evolution-net:
    external: true
